### ISSUE TITLE
Discussion (other)(tbc)(Core Support)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#158]
Seems to me we need help on Core sport  ...including broken spells fixes..
It would be great if more would join and help with this project...
Just saying... i can report many many more issues...but i don't think u have the time to fix them all..alone

**Comment by Salja** [comment]
The problem is atm we have summer the most ppls have not fun to work wehn the summer is nice xD :-) 
You can report all time by time will all fixes for both core database sd2, i habe here a lot of old patches for me what need rewirte than can apply to core, yes your right alone is very slow and hard but on last month we maked a big step with the database

**Comment by Salja** [comment]
Other point to found new staff is we need a new logo and videos than we can post on forums more ppls will use the core and help

**Comment by Salja** [comment]
Btw im 1000000% sure you not found a better working tbc open source tbc server as this project here a lot of quests are working epic things working npc have waypoints and not stand only so i think we need only post on few forums
