### ISSUE TITLE
Data transfer error(database/mangos one)

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#178]
executing the sql work's fine but when transferring from one db to another (with Navicat)

[Err] [Dtf] 1366 - bla bla bla..........
[Err] [Dtf] Finished - Unsuccessfully

**Comment by Salja** [comment]
Navicat is the problem i have same error on navicat hmm not sure way but i will look on sqlyog works all fine and other clients

**Comment by Mibu86** [comment]
fact is that it worked for me on executing the db sql in my navicat but i cant put it on the server msql ..because of the error lol..

**Comment by Salja** [comment]
Hmm maybe a other can say what tyraela maybe

**Comment by Mibu86** [comment]
Found fix :)) just copy paste the tables from one db to another without the export function...and not all of them at once..it worked

**Comment by Salja** [comment]
Sounds good xD :-)

**Comment by ghost** [comment]
Sorry it's a bit late, but I thought I should throw in that TrinityCore warns about using NaviCat:

**Do not use Navicat!!**
 Due to Navicat not being able to handle // style comments (standard SQL), including incidents of failed imports despite positive feedback from the program itself, we advise all users to stay VERY clear of this product - you have been warned.

**Comment by Salja** [comment]
Yepp thats right navicat is bad option for mysql clients i use sice years sqlyog or terminal from linux 

For test things i buyed navicat for mac and on import make errors export make errors

**Comment by Mibu86** [comment]
Only shit i have been using...always :)
