### ISSUE TITLE
Quest: Warlock Quest for Infernal

### ISSUE THREAD

**Issue by Warchas** [CoronaCore/Issues#210]
Unable to revive kroshius which is needed for the quest to be completed.

**Comment by Salja** [comment]
Pls quest entry

**Comment by Mibu86** [comment]
quest=7603
From wut i remember there is an issue with "item=18626"(Fel Fire) that requires a certain invisible object to be near Kroshius for use . I remember it was missing fixxed once.

**Comment by Salja** [comment]
Ah i thunk thats i ahve fixed long time ago on classic maybe 2 years ago or longer xd

**Comment by Salja** [comment]
i will look tomorrow of it thanks

**Comment by Mibu86** [comment]
Add 300049 object on Kroshius position.. and it's fixxed
True i believe it should be spawned via script...but who cares is an invisible object even for GM.

**Comment by Salja** [comment]
@Mibu86 you half right but right the gameobject is already spawnd but have worng yxzo

delete from gameobject where guid = 99894;
insert into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('99894','300049','1','1','5781.92','-967.929','412.328','0','0','0','0','1','180','0','1');

thanks for pointing the fix is right i will add to repo later

**Comment by Mibu86** [comment]
My bad ..on the other half..should have searched for the object first to see if the spawn already exist..i assumed it did-int . Next time all search for it first

**Comment by Mibu86** [comment]
Need one more fix on https://github.com/CoronaCore/Issues/issues/211 and all warlock class spell's quest's would be cool

**Comment by Salja** [comment]
yeah sure i look today atm not on dev pc so i cant push to repo
