### ISSUE TITLE
Got a mail invite from PlayTBC.com

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#260]
got any ideea?

**Comment by ghost** [comment]
Looks like a new project starting next year. The idea is good, just hope they get enough players.
Their statements look like they mean to be serious about accurate gameplay.
If the server setup has been tested as much as they say, it will be worth checking out.
Not many members yet, though, since the server is not online until next year.
http://playtbc.com/forums/memberlist.php

**Comment by Mibu86** [comment]
just got a Tester invite for me and friends...if youre interested in testing let me know

**Comment by ghost** [comment]
Thanks for the offer, but I won't have time to do any testing. :)

**Comment by Mibu86** [comment]
i went i tested 1 hour.today ..everything is shit..worse then normal mangos emulator..
